name: Run Jazzer against Dapr SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.3.1"]
        
    steps:
    - uses: actions/checkout@v2
    - name: git-bash
      run: |
         chmod +x ./entrypoint.sh
         ./entrypoint.sh --version ${{matrix.version}} --package io.dapr.client --class DaprClientBuilder --methods 'withObjectSerializer withStateSerializer' --keep-going=1
      shell: bash

    - name: Upload Crash
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: artifacts
        path: ./fuzzing

