name: Run Jazzer against Dapr SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker run cifuzz/jazzer-autofuzz io.dapr:dapr-sdk:1.3.1 io.dapr.client.DaprClientBuilder::withObjectSerializer

