name: Run Jazzer against Dapr SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.3.0, 1.3.1]
        package: [io.dapr.client]
        include:
          - package: io.dapr.client
            class: DaprClientBuilder
            methods: 'withObjectSerializer withStateSerializer'
          - package: io.dapr.client
            class: DaprClientGrpc
            methods: 'waitForSidecar publishEvent invokeMethod'
        
    steps:
    - uses: actions/checkout@v2
    - name: git-bash
      run: |
         chmod +x ./entrypoint.sh
         ./entrypoint.sh --version ${{matrix.version}} --package ${{matrix.package}} --class ${{matrix.class}} --methods ${{matrix.methods}} --keep-going=1
      shell: bash

    - name: Upload Crash
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: artifacts
        path: ./fuzzing

